version: "3"

volumes:
  choiceinvest_volume:

services:
  restapi:
    image: "${DOCKER_IMAGE_BACKEND?Varible not set}"
    build:
      context: .
      dockerfile: restapi.dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: "${DOCKER_IMAGE_POSTGRES?Postgres image not set}"
    volumes:
      - choiceinvest_volume:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env

  pgadmin:
    image: "${DOCKER_IMAGE_PGADMIN}"
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - postgres